config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions
  resources :users
  resources :instruments

  get 'login'   => 'user_sessions#new',     as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  root to: 'instruments#index'
end

app/models/account.rb
class Account < ActiveRecord::Base

  # validate name subdomain presence uniquenes
  # validate subdomain RegExp /^[a-z\d]+([-_][a-z\d]+)*$/i

  after_create :create_schema

  def create_schema
    con = self.class.connection
    con.execute "CREATE SCHEMA #{subdomain}"
    sql = open("#{Rails.root}/db/structure.sql", 'r').read.gsub(/^SET search_path .*;/, '')
    scope_schema do
      con.execute sql
      con.execute "DROP TABLE schema_migrations, #{self.class.table_name}"
    end
  end

  def scope_schema *paths
    con = self.class.connection
    original_search_path = con.schema_search_path
    con.schema_search_path = [subdomain, *paths].join ','
    yield
  ensure
    con.schema_search_path = original_search_path
  end
end

app/models/concerns/retry_methods.rb
module RetryMethods
  def retry_on_error er, n = 1, &block
    count = 1
    begin
      block.call
    rescue er
      count+= 1 and retry if count <= n
      raise
    end
  end

  def save_and_retry_on_unique *args
    retry_on_error ActiveRecord::RecordNotUnique do
      save *args
    end
  end
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  include RetryMethods

  validates :reference, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base

  # validate name subdomain presence uniquenes
  # validate subdomain RegExp /^[a-z\d]+([-_][a-z\d]+)*$/i

  after_create :create_schema

  def create_schema
    con = self.class.connection
    con.execute "CREATE SCHEMA #{subdomain}"
    sql = open("#{Rails.root}/db/structure.sql", 'r').read.gsub(/^SET search_path .*;/, '')
    scope_schema do
      con.execute sql
      con.execute "DROP TABLE schema_migrations, #{self.class.table_name}"
    end
  end

  def scope_schema *paths
    con = self.class.connection
    original_search_path = con.schema_search_path
    con.schema_search_path = [subdomain, *paths].join ','
    yield
  ensure
    con.schema_search_path = original_search_path
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include RetryMethods

  authenticates_with_sorcery!
  
  validates :name,  presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true, length: { minimum: 3 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login
  around_filter :scope_current_account

private
  def not_authenticated
      redirect_to login_path, alert: 'Please login first'
  end

  def current_account
    if request.subdomain.present?
      @current_account ||= Account.find_by_subdomain! request.subdomain
    end
  end
  helper_method :current_account

  def scope_current_account &block
    if current_account
      current_account.scope_schema 'public', &block
    else
      yield
    end
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  respond_to :html

  def index
    @instruments = Instrument.all
    respond_with @instruments
  end

  def new
    @instrument ||= Instrument.new
  end

  def show
    @instrument = Instrument.find(params[:id])
    respond_with @instrument
  end

  def create
    @instrument = Instrument.new instrument_params
    flash[:notice] = 'Instrument was successfully created' if @instrument.save_and_retry_on_unique
    respond_with @instrument
  end

  def edit
    @instrument = Instrument.find(params[:id])
    respond_with @instrument
  end

  def update
    @instrument = Instrument.find(params[:id])
    flash[:notice] = 'Instrument was successfully updated' if @instrument.update_attributes(instrument_params)
    respond_with @instrument
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    @instrument.destroy
    flash[:notice] = 'Instrument was successfully destroyed' 
    respond_with @instrument
  end

protected
  def instrument_params
    params.require(:instrument)
          .permit(:reference,
                  :description,
                  :manufacturer, :model, :sn, :pn,
                  :remarks)
          .delete_if{ |k, v| v.blank? }
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_action :require_login, except: :destroy

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:login][:email], params[:login][:password], params[:login][:remember])
      redirect_back_or_to root_url, notice: 'Login successful'
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to :login, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :html

  skip_before_action :require_login, only: [:index, :new, :create]

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    respond_with @users
  end

  def show
  end

  def new
    @user ||= User.new
  end

  def edit
    respond_with @user
  end

  def create
    @user = User.new(user_params)
    if @user.save_and_retry_on_unique && login(user_params[:email], user_params[:password])
      flash[:notice] = 'User was successfully created and logged in'
    end
    respond_with @user, location: root_url
  end

  def update
    flash[:notice] = 'User was successfully updated' if @user.update_attributes(user_params)
    respond_with @user
  end

  def destroy
    @user.destroy
    flash[:notice] = 'User was successfully destroyed' 
    respond_with @user, location: root_url
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def present object, klass = nil
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new object, self
    yield presenter if block_given?
    presenter
  end
end

app/views/instruments/_form.html.slim
= simple_form_for @instrument do |f|
  fieldset 
    = f.error_notification
    = f.error :base

    section.form-inputs
      = f.input :reference
      = f.input :description
      = f.input :manufacturer
      = f.input :model
      = f.input :sn, label: 'Serial Number'
      = f.input :pn, label: 'Part Number'
      = f.input :remarks

    section.form-actions
      = f.button :submit, data: { disable_with: 'Submitting...' }

app/views/instruments/_instrument.html.slim
- present instrument do |i|
  .summary
    .reference
      h3= i.reference
    .details
      h4= i.description
      p= i.details
    .secondary_actions
      = i.edit_link
      = i.destroy_link

app/views/instruments/edit.html.slim
h1 Edit Instrument

= render 'form'

app/views/instruments/index.html.slim
h1 Instruments

.main_actions
  = link_to 'New Instrument', new_instrument_path

- if @instruments.empty?
  p No instruments found.
- else
  = render @instruments

app/views/instruments/new.html.slim
h1 New Instrument

= render 'form'

app/views/instruments/show.html.slim
h1= @instrument.reference
section
  dl
    dt Description
    dd= @instrument.description
section
  dl
    dt Manufacturer
    dd= @instrument.manufacturer
    dt Model
    dd= @instrument.model
    dt Serial Number
    dd= @instrument.sn
    dt Part Number
    dd= @instrument.pn
section
  dl
    dt Remarks
    dd= @instrument.remarks

section.secondary_actions
  = link_to 'Edit', edit_instrument_path(@instrument)
  = link_to 'Back to Instrument list', instruments_path, class: 'secondary'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div[class="alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}" data-alert]
      = content_tag :div, msg
      a.close[href="#"]
        | ×

app/views/layouts/_navigation.html.slim
/ navigation styled for Zurb Foundation 5
nav.top-bar[data-topbar]
  ul.title-area
    li.name
      = link_to 'Home', root_path
    li.toggle-topbar.menu-icon
      a[href="#"]
        Menu
  .top-bar-section
    ul
      == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
ul.right
  - if current_user
    li.has-dropdown
      = link_to current_user.name, '#'
      ul.dropdown
        li= link_to 'Edit Profile', edit_user_path(current_user.id)
        li.divider
        li= link_to 'Logout', :logout, method: :post
  - else
    li= link_to 'Login', :login
    li= link_to 'Register', new_user_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Metron'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Metron'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag 'vendor/modernizr'
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/user_sessions/_form.html.slim
= simple_form_for :login, { url: user_sessions_path } do |f|
  fieldset 
    = f.error_notification
    = f.error :base

    section.form-inputs
      = f.input :email
      = f.input :password
      = f.input :remember, as: :boolean, label: 'Keep me logged in'

    section.form-actions
      = f.button :submit, 'Log In', data: { disable_with: 'Logging in...' }

app/views/user_sessions/new.html.slim
h1 Log In

== render 'form'

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  fieldset 
    = f.error_notification
    = f.error :base

    section.form-inputs
      = f.input :name
      = f.input :email
      = f.input :password
      = f.input :password_confirmation

    section.form-actions
      = f.button :submit, data: { disable_with: 'Submitting...' }

app/views/users/_user.html.slim
- present user do |u|
  .summary
    .reference
      h3= u.name
    .details
      h4= u.email
      p= u.details
    .secondary_actions
      = u.edit_link
      = u.destroy_link

app/views/users/edit.html.slim
h1 Edit user

== render 'form'

app/views/users/index.html.slim
h1 Users

.main_actions
  = link_to 'New User', new_user_path

- if @users.empty?
  p No users found.
- else
  = render @users

app/views/users/new.html.slim
h1 New user

== render 'form'

app/views/users/show.html.slim
h1= @user.name
section
  dl
    dt e-mail
    dd= @user.email

section.secondary_actions
  = link_to 'Edit', edit_user_path(@user)
  = link_to 'Home', root_url, class: 'secondary'